return function() {
    // reset all the edit values
    $setUser('editDOD', '')
    $setUser('editDOB', '')
    $setUser('editEmail', '')
    $setUser('editFirstName', '')
    $setUser('editMiddleName', '')
    $setUser('editLastName', '')
    $setUser('editHomePhone', '')
    $setUser('editMarital', '')
    $setUser('editMobile', '')
    $setUser('editNHS', '')
    $setUser('editSalutation', '')
    $setUser('editSex', '')
    $setUser('editCity', '')
    $setUser('editPostCode', '')
    $setUser('editAddress', '')
    $setUser('editCounty', '')
    $setUser('editAddress2', '')

    // Reset all the user values
    $setUser('firstName', '')
    $setUser('lastName', '')
    $setUser('createAddress', '')
    $setUser('createCity', '')
    $setUser('createCounty', '')
    $setUser('createCountry', '')
    $setUser('createPostCode', '')
    $setUser('createMobile', '')
    $setUser('createEmail', '')
    $setUser('createHome', '')
    $setUser('createDob', '')
    $setUser('createSex', '')
    $setUser('createSalutation', '')
    $setUser('createAddress2', '')
}